// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCryo9M5dQHd50jJ7UG6eyL328PxEdsFpc',
    appId: '1:598771915318:web:4285c81e605af6a4401697',
    messagingSenderId: '598771915318',
    projectId: 'bus-management-a7917',
    authDomain: 'bus-management-a7917.firebaseapp.com',
    databaseURL: 'https://bus-management-a7917-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-a7917.firebasestorage.app',
    measurementId: 'G-6F9CV6RM5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpAFXC5zyHhkpjri7dXL5TyWHB7mT5XU',
    appId: '1:598771915318:android:0d5a7b465ef98c95401697',
    messagingSenderId: '598771915318',
    projectId: 'bus-management-a7917',
    databaseURL: 'https://bus-management-a7917-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-a7917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBem4eBnqK6ivAZALaccX3kdfoaNTbo1Ag',
    appId: '1:598771915318:ios:ab338242942801cf401697',
    messagingSenderId: '598771915318',
    projectId: 'bus-management-a7917',
    databaseURL: 'https://bus-management-a7917-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-a7917.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBem4eBnqK6ivAZALaccX3kdfoaNTbo1Ag',
    appId: '1:598771915318:ios:ab338242942801cf401697',
    messagingSenderId: '598771915318',
    projectId: 'bus-management-a7917',
    databaseURL: 'https://bus-management-a7917-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-a7917.firebasestorage.app',
    iosBundleId: 'com.example.firstly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCryo9M5dQHd50jJ7UG6eyL328PxEdsFpc',
    appId: '1:598771915318:web:990150ebd2018cdd401697',
    messagingSenderId: '598771915318',
    projectId: 'bus-management-a7917',
    authDomain: 'bus-management-a7917.firebaseapp.com',
    databaseURL: 'https://bus-management-a7917-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bus-management-a7917.firebasestorage.app',
    measurementId: 'G-DNWYKSWDWQ',
  );
}
